<?php
/**
 * @file
 *
 * Module core file.
 */

/**
 * Implements hook_menu().
 */
function ding_item_cache_menu() {
  $items = array();

  $items['admin/config/ding/ding_item_cache'] = array(
    'title' => 'Ding item cache',
    'description' => 'Clear caches of certain modules relying on Ding item caching.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_item_cache_clear_form'),
    'access arguments' => array('system_performance_settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Form that allows to clear certain caches.
 */
function ding_item_cache_clear_form($form, &$form_state) {
  $cache_info = module_invoke_all('ding_item_cache');

  $form['ding_item_cache_modules'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Modules'),
    '#description' => t('Select those modules which cache has to be cleared'),
    '#required' => TRUE,
    '#options' => $cache_info,
  );

  $form['ding_item_cache_clear'] = array(
    '#type' => 'submit',
    '#value' => t('Clear caches'),
  );

  return $form;
}

/**
 * Cache clear procedure.
 */
function ding_item_cache_clear_form_submit($form, &$form_state) {
  if (count($form_state['values']['ding_item_cache_modules'])) {
    $items_deleted = 0;
    foreach ($form_state['values']['ding_item_cache_modules'] as $module) {
      $items_deleted +=
        db_delete('cache_ding_item')
          ->condition('cid', "$module%", 'LIKE')
          ->execute();
    }

    drupal_set_message(t('Ding item cache has been cleared'));
  }
}
